import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/sections/Navbar'
import Footer from '@/components/sections/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" style={{scrollBehavior: 'smooth'}}>
      <body className={inter.className + ' overflow-x-hidden transition-all  scroll-smooth'}>
        <Navbar/>
        {children}
        <Footer/>
        </body>
    </html>
  )
}
